/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jjsg.weather

import io.kotest.matchers.shouldNotBe
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun `app has a greeting`() {
        val classUnderTest = App()

        classUnderTest.greeting shouldNotBe null
    }
}
